### ISSUE TITLE
Stake Client v2 checklist

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/stake-client#3]
- [x]  bond & bond extra to relaychain
- [x]  unbond & rebond
- [x]  transfer to parachain
- [x]  call trigger new era
- [x]  response from relaychain (4)
- [x]  record rewards & slash
- [ ]  reboot recover (scan the subscan db & subql) (read era history from parachain)
- [x]  local db
- [x]  nominate certain validators
- [x] #7 
- [ ] #6
